#!/bin/sh
#
# @name Gazebo x500 depth
#
# @type Quadrotor
#

PX4_GZ_MODEL=${PX4_GZ_MODEL:=x500_fpv_cam}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=sonoma}
PX4_GZ_MODEL_POSE=${PX4_GZ_MODEL_POSE:=278.08 -134.22 2.86 0.02 0 0.97}

. ${R}etc/init.d-posix/airframes/4001_gz_x500
